// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyB9uYvulSY5-UD0ogmH5maayPW4e_q75Ig",
      authDomain: "ppnongnghiep.firebaseapp.com",
      projectId: "ppnongnghiep",
      storageBucket: "ppnongnghiep.firebasestorage.app",
      messagingSenderId: "608328512668",
      appId: "1:608328512668:web:a6f4112922d25cd04d6959",
      measurementId: "G-6WND34B31K"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC7In0fHm4R-1zeZKMdFwxWUH4Gii159Y',
    appId: '1:552098486468:ios:efa7adf7532124239a9191',
    messagingSenderId: '552098486468',
    projectId: 'device-streaming-4a671bb5',
    storageBucket: 'device-streaming-4a671bb5.firebasestorage.app',
    iosBundleId: 'com.example.doandidonghoa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC7In0fHm4R-1zeZKMdFwxWUH4Gii159Y',
    appId: '1:552098486468:ios:efa7adf7532124239a9191',
    messagingSenderId: '552098486468',
    projectId: 'device-streaming-4a671bb5',
    storageBucket: 'device-streaming-4a671bb5.firebasestorage.app',
    iosBundleId: 'com.example.doandidonghoa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJRutc47RqJzjqdDFq2At4SvSOd8BvgmQ',
    appId: '1:552098486468:web:31048a5c43a37a489a9191',
    messagingSenderId: '552098486468',
    projectId: 'device-streaming-4a671bb5',
    authDomain: 'device-streaming-4a671bb5.firebaseapp.com',
    storageBucket: 'device-streaming-4a671bb5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhiJK_c5qNDk7FWKkoc2rmxyeS4PCiLww',
    appId: '1:552098486468:android:4cf7d8697207a0319a9191',
    messagingSenderId: '552098486468',
    projectId: 'device-streaming-4a671bb5',
    storageBucket: 'device-streaming-4a671bb5.firebasestorage.app',
  );

}